controller_manager:
  ros__parameters:
    update_rate: 50

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController


ackermann_steering_controller:
  ros__parameters:
    # ─────────────────────────────
    # REQUIRED JOINT NAMES
    # ─────────────────────────────
    traction_joints_names:
      - right_front_wheel_joint
      - left_front_wheel_joint

    steering_joints_names:
      - right_rear_steer_joint
      - left_rear_steer_joint

    # ─────────────────────────────
    # REQUIRED GEOMETRY PARAMETERS
    # ─────────────────────────────
    wheelbase: 0.215
    traction_track_width: 0.150
    rear_wheel_track: 0.140
    traction_wheels_radius: 0.0425
    steering_wheels_radius: 0.0375

    # ─────────────────────────────
    # ODOMETRY
    # ─────────────────────────────
    publish_rate: 50.0
    enable_odom_tf: true
    open_loop: false
    position_feedback: false

    # Ensure only the correct number of interfaces are exported
    reference_limit_min: -1.0
    reference_limit_max: 1.0

